name: CI_test1
on:
  push:
  pull_request:
    types: [opened, edited]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        with:
          build: npm run build
          start: npx wdio wdio.conf.js
