name: CI_test1
on:
  push:
  pull_request:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone ny repo
        uses: actions/checkout@v1
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 12.20.0
