name: CI_test1
on:
  push:
  pull_request:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Ls folder
          uses: ls -la
